'use client'
import {useMemo,useState} from 'react'; import {propertyTypes,services,frequency,condition} from '../data/catalog'; import {supabaseBrowser} from '../lib/supabase-browser';
type Qty=Record<string,number>;
export default function QuoteBuilder(){
 const [step,setStep]=useState(1),[property,setProperty]=useState('single'),[sqft,setSqft]=useState(1800),[beds,setBeds]=useState(3),[baths,setBaths]=useState(2),[floors,setFloors]=useState(2),[picked,setPicked]=useState<string[]>(['bathroom','sweepmop']),[qty,setQty]=useState<Qty>({desks:10,trash:6,diningtables:10,examrooms:4}),[freq,setFreq]=useState('once'),[cond,setCond]=useState('standard'),[contact,setContact]=useState({name:'',email:'',phone:'',address:'',date:''}),[message,setMessage]=useState('');
 const visible=services.filter(s=>s.property.includes('all')||s.property.includes(property));
 const toggle=(id:string)=>setPicked(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);
 const calc=(s:(typeof services)[number])=>{if(s.unit==='sqft')return s.price*sqft;if(s.unit==='bath')return s.price*baths;if(s.unit==='room')return s.price*beds;if(s.unit==='each')return s.price*(qty[s.id]||1);return s.price};
 const raw=useMemo(()=>picked.reduce((n,id)=>{const s=services.find(x=>x.id===id);return n+(s?calc(s):0)},0),[picked,sqft,beds,baths,qty]);
 const f=frequency.find(x=>x.id===freq)!,c=condition.find(x=>x.id===cond)!; const adjusted=raw*c.multiplier; const discount=adjusted*f.discount; const total=Math.max(85,adjusted-discount);
 const save=async()=>{setMessage('Guardando…');const sb=supabaseBrowser();const payload={property_type:property,square_feet:sqft,bedrooms:beds,bathrooms:baths,frequency:freq,subtotal:adjusted,discount,total,status:'saved'};if(sb){const {data:{user}}=await sb.auth.getUser();if(user){const {error}=await sb.from('quotes').insert({...payload,user_id:user.id});setMessage(error?'No se pudo guardar: '+error.message:'Cotización guardada en tu cuenta.');return}}localStorage.setItem('cleanpro-last-quote',JSON.stringify({...payload,picked,contact,created_at:new Date().toISOString()}));setMessage('Cotización guardada en este dispositivo. Al conectar Supabase se guardará en la cuenta del cliente.')};
 const next=()=>setStep(s=>Math.min(5,s+1)),back=()=>setStep(s=>Math.max(1,s-1));
 return <section className="builder"><div className="steps">{['Propiedad','Detalles','Servicios','Frecuencia','Resumen'].map((x,i)=><span className={step===i+1?'active':''} key={x}><i>{i+1}</i>{x}</span>)}</div>
 {step===1&&<><h2>¿Qué tipo de propiedad tienes?</h2><p className="lead">Selecciona el tipo para mostrar tareas apropiadas.</p><div className="propertyGrid">{propertyTypes.map(p=><button key={p.id} className={property===p.id?'selected':''} onClick={()=>setProperty(p.id)}><span>{p.icon}</span><b>{p.name}</b><small>{p.group}</small></button>)}</div></>}
 {step===2&&<><h2>Cuéntanos sobre tu propiedad</h2><p className="lead">Puedes escribir los datos reales; los tipos de vivienda no fijan automáticamente el tamaño.</p><div className="details"><label>Pies cuadrados (ft²)<input min="100" type="number" value={sqft} onChange={e=>setSqft(+e.target.value||0)}/></label><label>Dormitorios / cuartos<input min="0" type="number" value={beds} onChange={e=>setBeds(+e.target.value||0)}/></label><label>Baños<input min="0" step=".5" type="number" value={baths} onChange={e=>setBaths(+e.target.value||0)}/></label><label>Pisos / niveles<input min="1" type="number" value={floors} onChange={e=>setFloors(+e.target.value||1)}/></label></div><h3>Nivel de limpieza</h3><div className="choiceRow">{condition.map(x=><button className={cond===x.id?'selected':''} onClick={()=>setCond(x.id)} key={x.id}>{x.name}<small>{x.multiplier>1?`× ${x.multiplier}`:'Mantenimiento regular'}</small></button>)}</div></>}
 {step===3&&<><h2>¿Qué quieres limpiar?</h2><p className="lead">Selecciona solamente lo que necesitas. Toca de nuevo para eliminarlo.</p><div className="serviceGrid">{visible.map(s=><button key={s.id} className={picked.includes(s.id)?'selected':''} onClick={()=>toggle(s.id)}><div><b>{picked.includes(s.id)?'✓ ':''}{s.name}</b><p>{s.description}</p><small>{s.unit==='sqft'?`$${s.price}/ft²`:s.unit==='each'?`$${s.price} c/u`:`desde $${s.price}`}</small></div>{s.unit==='each'&&picked.includes(s.id)&&<input aria-label={'Cantidad '+s.name} type="number" min="1" value={qty[s.id]||1} onClick={e=>e.stopPropagation()} onChange={e=>setQty({...qty,[s.id]:+e.target.value||1})}/>}</button>)}</div></>}
 {step===4&&<><h2>¿Con qué frecuencia necesitas el servicio?</h2><p className="lead">El descuento se calcula automáticamente.</p><div className="frequency">{frequency.map(x=><button className={freq===x.id?'selected':''} onClick={()=>setFreq(x.id)} key={x.id}><b>{x.name}</b><small>{x.discount?`Ahorra ${x.discount*100}%`:'Precio regular'}</small></button>)}</div><h3>Datos para la solicitud</h3><div className="details"><label>Nombre<input value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/></label><label>Email<input type="email" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></label><label>Teléfono<input value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></label><label>Dirección<input value={contact.address} onChange={e=>setContact({...contact,address:e.target.value})}/></label><label>Fecha preferida<input type="date" value={contact.date} onChange={e=>setContact({...contact,date:e.target.value})}/></label></div></>}
 {step===5&&<><h2>Tu cotización</h2><p className="lead">Revisa y elimina cualquier servicio antes de guardar o pagar.</p><div className="summary"><div><h3>{propertyTypes.find(x=>x.id===property)?.name}</h3><p>{sqft.toLocaleString()} ft² · {beds} cuartos · {baths} baños · {floors} niveles</p>{picked.map(id=>{const s=services.find(x=>x.id===id)!;return <div className="line" key={id}><span>{s.name}</span><span>${calc(s).toFixed(2)} <button onClick={()=>toggle(id)}>Eliminar</button></span></div>})}<div className="line"><span>Nivel: {c.name}</span><span>{c.multiplier>1?`×${c.multiplier}`:'—'}</span></div><div className="line"><span>Descuento {f.name}</span><span>-${discount.toFixed(2)}</span></div></div><div className="totalCard"><small>Total estimado por visita</small><strong>${total.toFixed(2)}</strong><button className="primary" onClick={save}>Guardar cotización</button><form action="/api/checkout" method="POST"><input type="hidden" name="amount" value={Math.round(total*100)}/><button className="pay" type="submit">Pagar / Reservar</button></form><small>Stripe se activa al agregar tus variables de entorno.</small></div></div>{message&&<p className="notice">{message}</p>}</>}
 <div className="navBtns">{step>1&&<button onClick={back}>← Atrás</button>}{step<5&&<button className="primary" onClick={next}>Siguiente →</button>}</div><div className="livePrice"><span>Estimado actual</span><b>${total.toFixed(2)}</b></div></section>}
